// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhlhisaedryjgfxuuhwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpobGhpc2FlZHJ5amdmeHV1aHdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NTg5NjksImV4cCI6MjA2NjMzNDk2OX0.fq4Baes7vCnegG682l3AhRX_BirFTrFy2tnYcSAvwYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);